modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="pisciculture" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Pisciculture" #mandatory
logoFile="logo.png" #optional
credits="PouffyDev, ChadVAFN" #optional
authors="PouffyDev" #optional

description='''

'''
[[dependencies.pisciculture]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.pisciculture]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
